api_platform:
  mapping:
    paths:
      [
        "%kernel.project_dir%/src/Entity",
        "%kernel.project_dir%/config/api_platform",
      ]
  collection:
    pagination:
      enabled: true
      client_enabled: true
      client_items_per_page: false
      items_per_page: 30

  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
