App\Entity\Order:
  attributes:
    id:
      groups: [ "read_order" , "write-order"]
    sentAt:
      groups: ["read_order" , "write-order"]
    addressDelivery:
      groups: ["read_order" , "write-order"]
    products:
      groups: ["read_order" , "write-order"]
    user:
      groups: ["read_order" , "write-order"]
    