App\Entity\Category:
  attributes:
    normalization_context:
      groups: ["read_category"]
    # denormalization_context:
    #   groups: ["write_category"]

  collectionOperations:
    get:
      path: /categorys
  itemOperations:
    get:
      method: "GET"
      path: "/category/{id}"
      requirements:
        id: '\d+'
