App\Entity\Category:
  attributes:
    normalization_context:
      groups: ["read_cat"]
    denormalization_context:
      groups: ["write_cat"]
  properties:
    products:
      subresource:
        resourceClass: 'App\Entity\Product'
        collection: false

  collectionOperations:
    get:
      path: /categorys
    get_category:
      method: "GET"
      path: /categorybyparent
      controller: App\Controller\CategoryController::categoryByParent
    #post: ~
  itemOperations:
    get:
      method: "GET"
      path: "/category/{id}"
      requirements:
        id: '\d+'
