App\Entity\OrderProduct:
  attributes:
    normalization_context:
      groups: ["read_orderP"]
    denormalization_context:
      groups: ["write_orderP"]

  collectionOperations:
    get: ~
    post: ~

  itemOperations:
    get: ~
    put: ~
    delete: ~
