App\Entity\Product:
  attributes:
    normalization_context:
      groups: ["read_product"]
    denormalization_context:
      groups: ["write_Product"]

  collectionOperations:
    get:
      path: /products
      filters: ["promo.range_filter"]
    post: ~

  itemOperations:
    get: ~
    #put: ~
    #delete: ~
