App\Entity\User:
  attributes:
    normalization_context:
      groups: ["read_user"]
    denormalization_context:
      groups: ["write_user"]

  collectionOperations:
    get: ~
    post: ~
  itemOperations:
    get: ~
    put: ~
    delete: ~
