App\Entity\User:
  attributes:
    normalization_context:
      groups: ["read_user"]
    denormalization_context:
      groups: ["write_user"]

  collectionOperations:
    get: ~

    post: ~

  itemOperations:
    get:
      method: "GET"
      path: "/user/{id}"
      requirements:
        id: '\d+'
    put: ~
    delete: ~
